// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.Data;

#nullable disable

namespace OnlineShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260730120704_AddOrdersTables")]
    partial class AddOrdersTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7717),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "لپ تاپ",
                            UpdatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7732)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7734),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "موبایل",
                            UpdatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7735)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7736),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "مانیتور",
                            UpdatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7736)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7737),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "تبلت",
                            UpdatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7738)
                        });
                });

            modelBuilder.Entity("OnlineShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineShop.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OnlineShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7838),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Laptop Dell",
                            Price = 35000000m,
                            Stock = 5,
                            UpdatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7839)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7845),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "HP Laptop",
                            Price = 42000000m,
                            Stock = 7,
                            UpdatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7846)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7848),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Samsung S25",
                            Price = 58000000m,
                            Stock = 12,
                            UpdatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7849)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7851),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "iPhone 17",
                            Price = 98000000m,
                            Stock = 4,
                            UpdatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7851)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7853),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "LG 27 Inch",
                            Price = 15000000m,
                            Stock = 10,
                            UpdatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7853)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7855),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Samsung Odyssey",
                            Price = 23000000m,
                            Stock = 6,
                            UpdatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7856)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7857),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "iPad Air",
                            Price = 47000000m,
                            Stock = 8,
                            UpdatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7858)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7859),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Galaxy Tab S10",
                            Price = 36000000m,
                            Stock = 9,
                            UpdatedAt = new DateTime(2026, 7, 30, 15, 37, 4, 536, DateTimeKind.Local).AddTicks(7860)
                        });
                });

            modelBuilder.Entity("OnlineShop.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("OnlineShop.Models.Category", b =>
                {
                    b.HasOne("OnlineShop.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OnlineShop.Models.OrderItem", b =>
                {
                    b.HasOne("OnlineShop.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.Models.Product", b =>
                {
                    b.HasOne("OnlineShop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlineShop.Models.ProductImage", b =>
                {
                    b.HasOne("OnlineShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.Models.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("OnlineShop.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
