// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.Data;

#nullable disable

namespace OnlineShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721131745_AddImageUrlToProduct")]
    partial class AddImageUrlToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1043),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "لپ تاپ",
                            UpdatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1055)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1058),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "موبایل",
                            UpdatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1059)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1060),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "مانیتور",
                            UpdatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1061)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1062),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "تبلت",
                            UpdatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1063)
                        });
                });

            modelBuilder.Entity("OnlineShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1186),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Laptop Dell",
                            Price = 35000000m,
                            Stock = 5,
                            UpdatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1187)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1195),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "HP Laptop",
                            Price = 42000000m,
                            Stock = 7,
                            UpdatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1196)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1199),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Samsung S25",
                            Price = 58000000m,
                            Stock = 12,
                            UpdatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1200)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1202),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "iPhone 17",
                            Price = 98000000m,
                            Stock = 4,
                            UpdatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1203)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1205),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "LG 27 Inch",
                            Price = 15000000m,
                            Stock = 10,
                            UpdatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1205)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1208),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Samsung Odyssey",
                            Price = 23000000m,
                            Stock = 6,
                            UpdatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1208)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1210),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "iPad Air",
                            Price = 47000000m,
                            Stock = 8,
                            UpdatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1211)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1213),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Galaxy Tab S10",
                            Price = 36000000m,
                            Stock = 9,
                            UpdatedAt = new DateTime(2026, 7, 21, 16, 47, 45, 418, DateTimeKind.Local).AddTicks(1214)
                        });
                });

            modelBuilder.Entity("OnlineShop.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("OnlineShop.Models.Category", b =>
                {
                    b.HasOne("OnlineShop.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OnlineShop.Models.Product", b =>
                {
                    b.HasOne("OnlineShop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlineShop.Models.ProductImage", b =>
                {
                    b.HasOne("OnlineShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.Models.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
